# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    
    docker:
      # Primary container image where all commands run
      - image: cimg/ruby:3.2.2-browsers
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: testuser
          REDIS_URL: redis://127.0.0.1:6379

    # Service container image available at `host: localhost`
      - image: cimg/redis:7.2.4
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: testuser
          POSTGRES_DB: mon_recette_test
    

    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      
      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-{{ checksum "Gemfile.lock" }}
            - rails-demo-

      # Create the directory for test results
      - run:
          name: Create Test Results Directory
          command: mkdir -p /tmp/test-results
            
      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle install

      - run: sudo apt install -y postgresql-client || true
      
      # Store bundle cache
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database Setup
          command: |
            if ! psql -U $POSTGRES_USER -d template1 -c "SELECT 1 FROM pg_database WHERE datname = '$POSTGRES_DB'" | grep -q 1; then
              bundle exec rake db:create
            fi

      - run:
          name: Waiting for Redis primary to be ready
          command: dockerize -wait tcp://localhost:6379 -timeout 1m

      - run:
          name: Parallel RSpec
          command: bundle exec rspec spec

      # Save artifacts
#      - store_test_results:
#          path: /tmp/test-results

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  main-workflow:
    jobs:
      - build